### ISSUE TITLE
Legend titles

### ISSUE THREAD

**Issue by jml1795** [USNavalResearchLaboratory/cxxplot#7]
Hi, thanks again for the really useful tool. I am looking for the ability to display legends on only a subset of the plotted items on a graph. For example, it I have three line plots on a graph but want the legend to reflect only items 1 and 2. I looked through some of the `qcustomplot` code and the graph and figure but wasn't seeing a way to make this happen. Do you have any suggestions on where to look? I can take a hack at adding the feature (if it doesn't already exist) if you can get me pointed in the right direction.

**Comment by niliopoulos** [comment]
Thank you for the suggestion!

I added legend entry visibility control. You can find an example in the examples folder under the name "13_legend_entry_visibility".
